source "http://rubygems.org"
ruby "3.0.1"
gem "sexp_processor", "~> 4.15"
gem "ruby_parser", "~> 3.17"
gem "ruby2ruby", "~> 2.4"
gem "bato", "~> 0.0.13"
gem "bundler"
gem "daemons", "~> 1.4"
gem "eventmachine", "~> 1.2"
gem "mustermann", "~> 1.1"
gem "rack", "~> 2.2"
gem "shotgun", "~> 0.9"
gem "tilt", "~> 2.0"
gem "sinatra", "~> 2.1"
gem "thin", "~> 1.8"
gem "rack-protection", "~> 2.1"
